[manager]
cwd = { fg = "#076678" }
hovered = { fg = "#3c3836", bg = "#ebdbb2" }
preview_hovered = { underline = true }
marker_selected = { fg = "#79740e", bg = "#79740e" }
marker_copied = { fg = "#b57614", bg = "#b57614" }
marker_cut = { fg = "#9d0006", bg = "#9d0006" }
tab_active = { fg = "#3c3836", bg = "#ebdbb2" }
tab_inactive = { fg = "#7c6f64", bg = "#d5c4a1" }
border_style = { fg = "#928374" }

[status]
mode_normal = { fg = "#fbf1c7", bg = "#076678", bold = true }
mode_select = { fg = "#fbf1c7", bg = "#79740e", bold = true }
mode_unset = { fg = "#fbf1c7", bg = "#8f3f71", bold = true }

[filetype]
rules = [
  { name = "*", fg = "#3c3836" },
  { name = "*/", fg = "#076678" }
]
