[manager]
ratio = [1, 4, 3]
sort_by = "modified"
sort_reverse = true
sort_dir_first = true
linemode = "size"
show_hidden = true

[preview]
tab_size = 2
max_width = 1000
max_height = 900

[log]
enabled = false
[flavor]
use = "gruvbox-light"
